"""empty message

Revision ID: c3668f8ffd0f
Revises: f9dcc9417807
Create Date: 2025-04-30 16:53:33.090774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3668f8ffd0f'
down_revision = 'f9dcc9417807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('representative_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('business_number', sa.String(length=12), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['business_number'])
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('registration_date')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('company_name')
        batch_op.drop_column('business_number')
        batch_op.drop_column('representative_name')

    # ### end Alembic commands ###
